### ISSUE TITLE
Setting table state via params

### ISSUE THREAD

**Issue by n8mlr** [treedoc/TreedocViewer#50]
Thank you so much for this project! I'm searching for a way to disable the Source and Tree views from appearing by default. I've seen the `options` parameter in https://github.com/treedoc/TreedocViewer/blob/master/src/models/TableParam.ts#L11, but am not sure how this string is parsed and how I might disable the Source and Tree state. Any help would be appreciated

**Comment by jianwu** [comment]
Thanks for the suggestion. The TableParam currently only used for the table route. e.g. : 

https://www.treedoc.org/?tableParam={title:test,%20jsonData:{a:1,%20b:2}}#/table

table router I was only use for testing. So it doesn't work well. Let me add proper support for those parameters. 

Curious what's your use case, are you plan to pass the data through URL or as embedded iframe. I have example of how to integrate it on existing page on the readme file: https://github.com/treedoc/TreedocViewer/blob/master/sample/embedded.html.

**Comment by n8mlr** [comment]
Thanks so much! My use case is to help non-technical team members understand a new information architecture I'm proposing for our products. I've learned initial experience of loading this page can be overwhelming for non-technical users: https://resonant-muffin-fb28f5.netlify.app/. 

Essentially, I want my audience to review the work i'm doing through the Table View, which allows them to easily navigate through different nodes without getting lost in markup or drill-down views.

I'd prefer to utilize the embedded iframe experience if I can, only because I'm loading Treedoc via a tiny react app.

**Comment by jianwu** [comment]
Added support of parameters: 
 
Example: 

https://www.treedoc.org/?data={a:1,b:{b1:2,b2:2},c:3}&initialPath=/b&title=tableTest&option={maxPane:table,parsers:[]}&tableConfig={Pagination:false,columns:[{field:b1}]}#/)](https://www.treedoc.org/?data={a:1,b:{b1:2,b2:2},c:3}&initialPath=/b&title=tableTest&option={maxPane:table,parsers:[]}&tableConfig={Pagination:false,columns:[{field:b1}]}#/

**Comment by n8mlr** [comment]
Thank you so much!
